### PR TITLE
feat: add first template for prs

### PR DESCRIPTION
**Pull request by GabSnow24**
## What was done?

This PR adds the feature of templating PRs for all repositories. 

## Why it was done?

This PR goal is to allow all repos to get templates and steps to follow in pull requests. 

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Confluence
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

[Shortcut Story - 30556](https://app.shortcut.com/cheddar/story/30556)

### CODE REVIEW

**Review by StefanSokicCheddar — CHANGES_REQUESTED** [review]
Hey @GabSnow24 appreciate the ownership here but I don't think this PR template makes sense for the whole organization because our repositories are so different and this would add extra work for each PR opened. Like we discussed in the DMs, once we get everyone to sign off on something that would work across repositories then we can go ahead and implement it, but putting it in one place is tough because we many different types of codebases like I mentioned.

**Comment by StefanSokicCheddar** [comment]
I do like the idea of adding the shortcut workflow here instead of in each repo though!!

**Comment by GabSnow24** [comment]
@StefanSokicCheddar thank you for taking some time to comment in the PR. It great that we are on the same page, the intention of the PR is to create a template together that can work across all repositories. 

Also, a good approach to get this done is start with an initial template (like this) and modify it by the necessity of projects. 

I'd love to hear your contribution on it to get it done also!

**Comment by StefanSokicCheddar** [comment]
@GabSnow24 and I talked about this in a meeting and he will follow up with opening this against each repo instead so this isn't applied to repos we dont own.

**Comment by StefanSokicCheddar** [comment]
@GabSnow24 mind closing this PR?

**Comment by StefanSokicCheddar** [comment]
we've moved to a different approach, closing this so it doesn't keep popping up for me on github

**Pull request closed without merging**
